Index/search/urls.py
from django.urls import path
from Index import views


urlpatterns = [
    path('', views.Index_Search(),name='index_search'),
]

Index/share/urls.py
from django.urls import path
from Index import views


urlpatterns = [
    path('', views.index_share,name='index_share'),
]

Index/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index_list,name='index'),
]

SecEssayCollect/urls.py
from django.contrib import admin
from django.urls import path,include
from Index.views import SecEssayDictAPI

urlpatterns = [
    path('sec-admin/', admin.site.urls),
    path('',include('Index.urls')),
    path('authentication/',include('Authentication.urls')),
    path('logout/',include('Authentication.logout.urls')),
    path('share/',include('Index.share.urls')),
    path('updatepasswd/',include('Authentication.updatepasswd.urls')),
    path('sort/', include('Index.sort.urls')),
    path('search/', include('Index.search.urls')),
    path('api/',SecEssayDictAPI.as_view(),name='api'),
    path('captchar/',include('Authentication.captchar.urls')),
]

Index/models.py
from django.db import models

# Create your models here.
class SecEssayDict(models.Model):
    index_title = models.CharField('标题',max_length=255)
    index_time = models.DateTimeField('时间')
    index_type = models.CharField('分类',max_length=25)
    index_url = models.CharField('链接', max_length=255)
    index_sharer = models.CharField('分享者',max_length=25,blank=True,editable=False)

Index/templates/CodeAudit.html
{% include "heade.html" %}

      <div class="row">
        <!-- 左侧目录栏（ -->
        <div class="col-md-3" >
          <div class="navbar-sider " id="sidebar">
        <!-- 左侧目录栏) -->
                            <a style="margin-left: 1.5em" href="/sort/WebVulnerability"class="list-group-item">Web漏洞</a>
                            <a style="margin-left: 1.5em" href="/sort/IntranetPenetration"class="list-group-item">内网渗透</a>
                            <a style="margin-left: 1.5em" href="/sort/PenetrationTest"class="list-group-item">渗透测试</a>
                            <a style="margin-left: 1.5em" href="/sort/CodeAudit"class="list-group-item">代码审计</a>
                            <a style="margin-left: 1.5em" href="/sort/Exploit"class="list-group-item">Exploit</a>
                            <a style="margin-left: 1.5em" href="/sort/Other"class="list-group-item">其它</a>

        <!-- 左侧目录栏 结束 ( -->            
          </div>
        </div>
        <!-- 左侧目录栏 结束 ) -->

        <!-- 右侧正文栏（ -->
        <div class="col-md-9">
            <!-- 教程正文主体部分） -->

<div class="content">
  <style>
      .content {
      width: 95%;
      margin:0 auto;
   }
      #top-time {
         width:40px;
      }
      #top-gory {
         width:70px;
      }
       #top-title {
         width:450px;
      }
      #top-click {
         width:70px;
      }
      #pager {
         left:50px;
      }
  </style>
      <table class="table table-striped table-bordered table-hover table" width="100">
   <thead>
      <tr>
      <th id="top-time">时间</th>
      <th id="top-title">标题</th>
      <th id="top-gory">分类</th>
      <th id="top-click">分享人</th>
    </tr>
  </thead>
  <tbody>
    
      {% for athlete in contacts %}
      <tr>
      <td>{{ athlete.index_time }}</td>
      <td><a href="{{ athlete.index_url }}" target="view_window" id="{{ athlete.id }}">{{ athlete.index_title }}</a></td>
      <td>{{ athlete.index_type }}</td>
      <td>{{ athlete.index_sharer }}</td>
      </tr>
    {% endfor %}
    
  </tbody>
</table>
   <ul class="pager" style="float:right">
    {% if contacts.has_previous %}
   <li><a href="?page={{ contacts.previous_page_number }}">Previous</a></li>
   {% endif %}
   {% if contacts.has_next %}
   <li><a href="?page={{ contacts.next_page_number }}">Next</a></li>
   </ul>
   {% endif %}
</div>
   </body>

        <!-- 右侧正文栏结束（ -->
        </div>
        <!-- 右侧正文栏结束 ）-->

</body>
</html>

Index/templates/IntranetPenetration.html
{% include "heade.html" %}

      <div class="row">
        <!-- 左侧目录栏（ -->
        <div class="col-md-3" >
          <div class="navbar-sider " id="sidebar">
        <!-- 左侧目录栏) -->
                            <a style="margin-left: 1.5em" href="/sort/WebVulnerability"class="list-group-item">Web漏洞</a>
                            <a style="margin-left: 1.5em" href="/sort/IntranetPenetration"class="list-group-item">内网渗透</a>
                            <a style="margin-left: 1.5em" href="/sort/PenetrationTest"class="list-group-item">渗透测试</a>
                            <a style="margin-left: 1.5em" href="/sort/CodeAudit"class="list-group-item">代码审计</a>
                            <a style="margin-left: 1.5em" href="/sort/Exploit"class="list-group-item">Exploit</a>
                            <a style="margin-left: 1.5em" href="/sort/Other"class="list-group-item">其它</a>

        <!-- 左侧目录栏 结束 ( -->            
          </div>
        </div>
        <!-- 左侧目录栏 结束 ) -->

        <!-- 右侧正文栏（ -->
        <div class="col-md-9">
            <!-- 教程正文主体部分） -->

<div class="content">
  <style>
      .content {
      width: 95%;
      margin:0 auto;
   }
      #top-time {
         width:40px;
      }
      #top-gory {
         width:70px;
      }
       #top-title {
         width:450px;
      }
      #top-click {
         width:70px;
      }
      #pager {
         left:50px;
      }
  </style>
      <table class="table table-striped table-bordered table-hover table" width="100">
   <thead>
      <tr>
      <th id="top-time">时间</th>
      <th id="top-title">标题</th>
      <th id="top-gory">分类</th>
      <th id="top-click">分享人</th>
    </tr>
  </thead>
  <tbody>
    
      {% for athlete in contacts %}
      <tr>
      <td>{{ athlete.index_time }}</td>
      <td><a href="{{ athlete.index_url }}" target="view_window" id="{{ athlete.id }}">{{ athlete.index_title }}</a></td>
      <td>{{ athlete.index_type }}</td>
      <td>{{ athlete.index_sharer }}</td>
      </tr>
    {% endfor %}
    
  </tbody>
</table>
   <ul class="pager" style="float:right">
    {% if contacts.has_previous %}
   <li><a href="?page={{ contacts.previous_page_number }}">Previous</a></li>
   {% endif %}
   {% if contacts.has_next %}
   <li><a href="?page={{ contacts.next_page_number }}">Next</a></li>
   </ul>
   {% endif %}
</div>
   </body>

        <!-- 右侧正文栏结束（ -->
        </div>
        <!-- 右侧正文栏结束 ）-->

</body>
</html>

Index/templates/Other.html
{% include "heade.html" %}

      <div class="row">
        <!-- 左侧目录栏（ -->
        <div class="col-md-3" >
          <div class="navbar-sider " id="sidebar">
        <!-- 左侧目录栏) -->
                            <a style="margin-left: 1.5em" href="/sort/WebVulnerability"class="list-group-item">Web漏洞</a>
                            <a style="margin-left: 1.5em" href="/sort/IntranetPenetration"class="list-group-item">内网渗透</a>
                            <a style="margin-left: 1.5em" href="/sort/PenetrationTest"class="list-group-item">渗透测试</a>
                            <a style="margin-left: 1.5em" href="/sort/CodeAudit"class="list-group-item">代码审计</a>
                            <a style="margin-left: 1.5em" href="/sort/Exploit"class="list-group-item">Exploit</a>
                            <a style="margin-left: 1.5em" href="/sort/Other"class="list-group-item">其它</a>

        <!-- 左侧目录栏 结束 ( -->            
          </div>
        </div>
        <!-- 左侧目录栏 结束 ) -->

        <!-- 右侧正文栏（ -->
        <div class="col-md-9">
            <!-- 教程正文主体部分） -->

<div class="content">
  <style>
      .content {
      width: 95%;
      margin:0 auto;
   }
      #top-time {
         width:40px;
      }
      #top-gory {
         width:70px;
      }
       #top-title {
         width:450px;
      }
      #top-click {
         width:70px;
      }
      #pager {
         left:50px;
      }
  </style>
      <table class="table table-striped table-bordered table-hover table" width="100">
   <thead>
      <tr>
      <th id="top-time">时间</th>
      <th id="top-title">标题</th>
      <th id="top-gory">分类</th>
      <th id="top-click">分享人</th>
    </tr>
  </thead>
  <tbody>
    
      {% for athlete in contacts %}
      <tr>
      <td>{{ athlete.index_time }}</td>
      <td><a href="{{ athlete.index_url }}" target="view_window" id="{{ athlete.id }}">{{ athlete.index_title }}</a></td>
      <td>{{ athlete.index_type }}</td>
      <td>{{ athlete.index_sharer }}</td>
      </tr>
    {% endfor %}
    
  </tbody>
</table>
   <ul class="pager" style="float:right">
    {% if contacts.has_previous %}
   <li><a href="?page={{ contacts.previous_page_number }}">Previous</a></li>
   {% endif %}
   {% if contacts.has_next %}
   <li><a href="?page={{ contacts.next_page_number }}">Next</a></li>
   </ul>
   {% endif %}
</div>
   </body>

        <!-- 右侧正文栏结束（ -->
        </div>
        <!-- 右侧正文栏结束 ）-->

</body>
</html>

Index/templates/PenetrationTest.html
{% include "heade.html" %}

      <div class="row">
        <!-- 左侧目录栏（ -->
        <div class="col-md-3" >
          <div class="navbar-sider " id="sidebar">
        <!-- 左侧目录栏) -->
                            <a style="margin-left: 1.5em" href="/sort/WebVulnerability"class="list-group-item">Web漏洞</a>
                            <a style="margin-left: 1.5em" href="/sort/IntranetPenetration"class="list-group-item">内网渗透</a>
                            <a style="margin-left: 1.5em" href="/sort/PenetrationTest"class="list-group-item">渗透测试</a>
                            <a style="margin-left: 1.5em" href="/sort/CodeAudit"class="list-group-item">代码审计</a>
                            <a style="margin-left: 1.5em" href="/sort/Exploit"class="list-group-item">Exploit</a>
                            <a style="margin-left: 1.5em" href="/sort/Other"class="list-group-item">其它</a>

        <!-- 左侧目录栏 结束 ( -->            
          </div>
        </div>
        <!-- 左侧目录栏 结束 ) -->

        <!-- 右侧正文栏（ -->
        <div class="col-md-9">
            <!-- 教程正文主体部分） -->

<div class="content">
  <style>
      .content {
      width: 95%;
      margin:0 auto;
   }
      #top-time {
         width:40px;
      }
      #top-gory {
         width:70px;
      }
       #top-title {
         width:450px;
      }
      #top-click {
         width:70px;
      }
      #pager {
         left:50px;
      }
  </style>
      <table class="table table-striped table-bordered table-hover table" width="100">
   <thead>
      <tr>
      <th id="top-time">时间</th>
      <th id="top-title">标题</th>
      <th id="top-gory">分类</th>
      <th id="top-click">分享人</th>
    </tr>
  </thead>
  <tbody>
    
      {% for athlete in contacts %}
      <tr>
      <td>{{ athlete.index_time }}</td>
      <td><a href="{{ athlete.index_url }}" target="view_window" id="{{ athlete.id }}">{{ athlete.index_title }}</a></td>
      <td>{{ athlete.index_type }}</td>
      <td>{{ athlete.index_sharer }}</td>
      </tr>
    {% endfor %}
    
  </tbody>
</table>
   <ul class="pager" style="float:right">
    {% if contacts.has_previous %}
   <li><a href="?page={{ contacts.previous_page_number }}">Previous</a></li>
   {% endif %}
   {% if contacts.has_next %}
   <li><a href="?page={{ contacts.next_page_number }}">Next</a></li>
   </ul>
   {% endif %}
</div>
   </body>

        <!-- 右侧正文栏结束（ -->
        </div>
        <!-- 右侧正文栏结束 ）-->

</body>
</html>

Index/templates/search.html
{% include "heade.html" %}
<html>
<body>
<div class="content">
  <style>
      .content {
      width: 60%;
      margin:0 auto;
   }
      #top-time {
         width:40px;
      }
      #top-gory {
         width:70px;
      }
       #top-title {
         width:450px;
      }
      #top-click {
         width:70px;
      }
      #pager {
         left:50px;
      }
  </style>
      <table class="table table-striped table-bordered table-hover table" width="100">
   <thead>
      <tr>
      <th id="top-time">时间</th>
      <th id="top-title">标题</th>
      <th id="top-gory">分类</th>
      <th id="top-click">分享人</th>
    </tr>
  </thead>
  <tbody>

{# 列出当前分页所对应的数据内容 #}
{% if show_all %}

      {% for athlete in page.object_list %}
      <tr>
      <td>{{ athlete.index_time }}</td>
      <td><a href="{{ athlete.index_url }}" target="view_window" id="{{ athlete.id }}">{{ athlete.index_title }}</a></td>
      <td>{{ athlete.index_type }}</td>
      <td>{{ athlete.index_sharer }}</td>
      </tr>
    {% endfor %}

{% else %}

    {# 导入自带高亮功能 #}
    {% load highlight %}
    {% for athlete in page.object_list %}
      <tr>
      <td>{{  athlete.object.index_time }}</td>
      <td><a href="{{ athlete.object.index_url }}" target="view_window" id="{{ athlete.object.id }}">{{ athlete.object.index_title }}</a></td>
      <td>{{ athlete.object.index_type }}</td>
      <td>{{ athlete.object.index_sharer }}</td>
      </tr>
    {% endfor %}

{% endif %}

  </tbody>
</table>
   <ul class="pager" style="float:right">

    {# 上一页的URL地址 #}
    {% if page.has_previous %}
        {% if query %}
   <li><a href="{% url 'index_search'%}?q={{ query }}&amp;page={{ page.previous_page_number }}">Previous</a></li>
        {% else %}
   <li><a href="{% url 'index_search'%}?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}
   {% endif %}


    {# 下一页的URL地址 #}
   {% if page.has_next %}
       {% if query %}
   <li><a href="{% url 'index_search'%}?q={{ query }}&amp;page={{ page.next_page_number }}">Next</a></li>
           {% else %}
   <li><a href="{% url 'index_search'%}?page={{ page.next_page_number }}">Next</a></li>
       {% endif %}
   {% endif %}
</ul>


</div>
   </body>
   <HR>
</html>

Index/templates/share.html
{% load staticfiles %}
<html>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <body>
    <link rel="stylesheet" type="text/css" href="{% static './css/bootstrap4.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static './css/style.css'%}">
        <section id="contact-area"  >
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 offset-lg-1"><!--start contact form-->
                        <div class="contact-box text-center">
                            <form id="ajax-contact" action="#" method="post"><div class="form-group row">
                                {% csrf_token %}
                                <div class="col-lg-6">
                                    <input type="text" class="form-control" id="id_index_title" name="index_title" placeholder="文章标题*" required>
                                </div>
                                <div class="col-lg-6">
{#                                <input type="text" class="form-control" id="id_index_type" name="index_type" placeholder="文章类型*" required>#}
                                    <select class="form-control" title="请选择" id="id_index_type" name="index_type"  required>
                                    <option value="" disabled selected hidden>文章类型*</option>
                                    <option value="Web漏洞">Web漏洞</option>
                                    <option value="内网渗透">内网渗透</option>
                                    <option value="渗透测试">渗透测试</option>
                                    <option value="代码审计">代码审计</option>
                                    <option value="Exploit">Exploit</option>
                                    <option value="其它">其它</option>
                                    </select>
                                </div>
                            </div>
                                <br>
                            <div class="form-group">
                                <input type="text" class="form-control" id="id_index_url" name="index_url" placeholder="文章URL连接">
                            </div>
                            <button type="submit" onclick="window.location.href = '../'">返回</button>
                            <button type="submit" style="margin-left:70px;">提 交</button>
                            <div id="form-messages"></div>
                        </form>
                    </div><!--end contact form-->
                </div>
            </div>
        </div>
    </section>
</body>
</html>